# Generated by Django 3.2 on 2021-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allclub', '0003_alter_clubinfo_clubkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='clubimage',
            field=models.ImageField(default='club_img/Club_defalut.png', upload_to='club_img/', verbose_name='社团图标'),
        ),
    ]
