# Generated by Django 3.2 on 2021-05-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubname', models.CharField(max_length=255, unique=True)),
                ('clubstar', models.FloatField()),
                ('create_time', models.DateField()),
            ],
        ),
    ]
