# Generated by Django 3.2 on 2021-05-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allclub', '0002_clubinfo_clubkind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='clubkind',
            field=models.CharField(default='体育运动类', max_length=255),
        ),
    ]
