# Generated by Django 3.2 on 2021-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allclub', '0004_clubinfo_clubimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='clubinfo',
            field=models.FileField(default='club_info/defaultpdf.pdf', upload_to='club_info/', verbose_name='社团详细信息'),
        ),
    ]
