# Generated by Django 3.2 on 2021-05-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signinaout', '0002_auto_20210513_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='head_image',
            field=models.ImageField(default='', upload_to='user_head/', verbose_name='头像'),
        ),
    ]
