# Generated by Django 3.2 on 2021-10-19 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signinaout', '0004_auto_20210529_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePasswordConfirmString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='signinaout.user')),
            ],
            options={
                'verbose_name': '修改密码确认码',
                'verbose_name_plural': '修改密码确认码',
                'ordering': ['-c_time'],
            },
        ),
    ]
