# Generated by Django 3.2 on 2021-05-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signinaout', '0003_user_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='check_image',
            field=models.ImageField(default='id_check/check_default.png', upload_to='id_check/', verbose_name='身份信息卡'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_checked',
            field=models.BooleanField(default=False),
        ),
    ]
